- hosts: web
  become: yes
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest

  - name: Start and enable httpd
    systemd:
      name: httpd
      state: started
      enabled: yes
      masked: no

  - name: Download Templates
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page259/digitco.zip
      dest: /var/www/html/
      
    
  - name: unzip
    yum: 
     name: unzip
     state: latest

  - name: unzip file
    unarchive:
     src: /var/www/html/digitco.zip
     dest: /var/www/html
     remote_src: yes

  - name:  move files 
    shell: mv /var/www/html/digitco/* /var/www/html/
    ignore_errors: yes

  # Disable SELinux
  - selinux:
      state: disabled
    ignore_errors: yes
  
  - name: 
    shell: chown -R apache:apache /var/www/html/

  - name:
    service:
      name: httpd
      state: restarted
