- hosts: centos
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: enable httpd
    systemd:
      name: httpd
      enabled: yes
  - name: install unzip
    yum:
      name: unzip
      state: latest
  - name: download templates
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page258/sentra.zip
      dest: /var/www/html
  - name: Extract sentra.zip
    unarchive:
      src: /var/www/html/sentra.zip
      dest: /var/www/html
      remote_src: yes
  - name: move files
    shell: rsync -r /var/www/html/templatemo_518_sentra/* /var/www/html/